import {
  LayoutDashboard,
  ShoppingBag,
  ShoppingCart,
  Package,
  Store,
  Percent,
  Users,
  UsersRound,
  Palette,
  ChartLine,
  Wrench,
  Settings,
  Search,
  Bell,
  LayoutGrid,
  Info,
  Ellipsis,
  EllipsisVertical,
  Rocket,
  User,
  QrCode,
  ExternalLink,
  Headphones,
  FileText,
  Keyboard,
  LogOut,
  Plus,
  RefreshCw,
  Download,
  Eye,
  EyeOff,
  SquarePen,
  Trash2,
  ListFilter,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  Menu,
  X,
  Check,
  Circle,
  Star,
  Heart,
  Mail,
  Calendar,
  TrendingUp,
  TrendingDown,
  Hourglass,
  Image,
  Camera,
  ArrowLeft,
  ArrowRight,
  MoveRight,
  ArrowUp,
  ArrowDown,
  CircleCheck,
  CircleX,
  TriangleAlert,
  BadgeCheck,
  CreditCard,
  Phone,
  Globe,
  BookOpen,
  Car,
  Lock,
  Share2,
  Tag,
  PiggyBank,
  Banknote,
  CircleDollarSign,
  Timer,
  Code,
  Terminal,
  Folder,
  KeyRound,
  Copy,
  Receipt,
  PackagePlus,
  UserPlus,
  ChartPie,
  Box,
  HandCoins,
  FileDown,
  SearchX,
  PackageSearch,
  SlidersHorizontal,
  Droplets,
  Zap,
  Sparkles,
  Gauge,
  Wallet,
  Landmark,
  ChartColumn,
  MoveUpRight,
  MoveDownRight,
  LoaderCircle,
  CircleQuestionMark,
  CircleDashed,
  AlarmClock,
  Shield,
  Type,
  Cloud,
  Database,
  CirclePlay,
  LogIn,
  CalendarX,
  MapPin,
  Minus,
  Columns2,
  LayoutPanelLeft,
  ClipboardList,
  ChartSpline,
} from 'lucide-vue-next'

import {
  PhHouse,
  PhUsersThree,
  PhTag,
  PhSealCheck,
  PhChartPieSlice,
  PhWallet,
} from '@phosphor-icons/vue'

export const icons = {
  home: LayoutDashboard,
  dashboard: LayoutDashboard,
  shopping_bag: ShoppingBag,
  'shopping-bag': ShoppingBag,
  shopping_cart: ShoppingCart,
  package: Package,
  store: Store,
  percent: Percent,
  users: Users,
  palette: Palette,
  'chart-line': ChartLine,
  chart_line: ChartLine,
  charts: ChartLine,
  wrench: Wrench,
  tools: Wrench,
  settings: Settings,
  search: Search,
  bell: Bell,
  notifications: Bell,
  'layout-grid': LayoutGrid,
  layout_grid: LayoutGrid,
  grid_view: LayoutGrid,
  info: Info,
  'more-horizontal': Ellipsis,
  more_horiz: Ellipsis,
  'more-vertical': EllipsisVertical,
  more_vert: EllipsisVertical,
  'more-2': EllipsisVertical,
  rocket: Rocket,
  user: User,
  qrcode: QrCode,
  'qr-code': QrCode,
  'external-link': ExternalLink,
  external_link: ExternalLink,
  headphones: Headphones,
  'file-text': FileText,
  file_text: FileText,
  keyboard: Keyboard,
  'log-out': LogOut,
  logout_box_line: LogOut,
  add: Plus,
  plus: Plus,
  refresh: RefreshCw,
  download: Download,
  file_download: FileDown,
  eye: Eye,
  visibility: Eye,
  visibility_off: EyeOff,
  'eye-off': EyeOff,
  edit: SquarePen,
  trash: Trash2,
  delete: Trash2,
  delete_forever: Trash2,
  'trash-2': Trash2,
  filter: ListFilter,
  filter_list: ListFilter,
  filter_alt: ListFilter,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_up: ChevronUp,
  chevron_down: ChevronDown,
  first_page: ChevronFirst,
  last_page: ChevronLast,
  menu: Menu,
  close: X,
  x: X,
  check: Check,
  check_circle: CircleCheck,
  circle_check: CircleCheck,
  checkbox_circle: CircleCheck,
  error: CircleX,
  cancel: CircleX,
  x_circle: CircleX,
  warning: TriangleAlert,
  alert: TriangleAlert,
  'alert-triangle': TriangleAlert,
  verified: BadgeCheck,
  verified_user: BadgeCheck,
  credit_card: CreditCard,
  call: Phone,
  phone: Phone,
  globe: Globe,
  language: Globe,
  book: BookOpen,
  menu_book: BookOpen,
  car: Car,
  directions_car: Car,
  lock: Lock,
  share: Share2,
  share_variant: Share2,
  tag: Tag,
  local_offer: Tag,
  piggy_bank: PiggyBank,
  banknote: Banknote,
  payments: CircleDollarSign,
  wallet: Wallet,
  account_balance: Landmark,
  bank: Landmark,
  timer: Timer,
  alarm: AlarmClock,
  code: Code,
  terminal: Terminal,
  folder: Folder,
  key: KeyRound,
  fingerprint: KeyRound,
  copy: Copy,
  receipt: Receipt,
  receipt_long: Receipt,
  add_shopping_cart: ShoppingCart,
  description: FileText,
  person_add: UserPlus,
  user_add: UserPlus,
  user_add_fill: UserPlus,
  chart_pie: ChartPie,
  pie_chart: ChartPie,
  trending_up: TrendingUp,
  trend_up: TrendingUp,
  trending_down: TrendingDown,
  trending_flat: MoveRight,
  trend_flat: MoveRight,
  hourglass: Hourglass,
  hourglass_top: Hourglass,
  image: Image,
  photo: Image,
  group: UsersRound,
  people: UsersRound,
  'user-group': UsersRound,
  user_group: UsersRound,
  camera: Camera,
  arrow_back: ArrowLeft,
  arrow_left: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_right: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_up: ArrowUp,
  arrow_downward: ArrowDown,
  arrow_down: ArrowDown,
  star: Star,
  favorite: Heart,
  heart: Heart,
  mail: Mail,
  envelope: Mail,
  calendar: Calendar,
  calendar_today: Calendar,
  circle: Circle,
  expand_more: ChevronDown,
  keyboard_arrow_down: ChevronDown,
  face: User,
  account_circle: User,
  skeleton: ChartColumn,
  line_weight: Ellipsis,
  vertical_align_center: ArrowUp,
  near_me: Zap,
  construction: Wrench,
  format_underline: Type,
  toggle_on: Check,
  cloud: Cloud,
  storage: Database,
  play_circle: CirclePlay,
  component_exchange: RefreshCw,
  font_download: Type,
  progress_activity: LoaderCircle,
  inventory_2: PackageSearch,
  search_off: SearchX,
  login: LogIn,
  event_busy: CalendarX,
  pin: MapPin,
  currency: HandCoins,
  balance: Landmark,
  chart: ChartLine,
  chart_spline: ChartSpline,
  help: CircleQuestionMark,
  question: CircleQuestionMark,
  minus: Minus,
  columns: Columns2,
}

export const highlightIcons = {
  users: PhUsersThree,
  tag: PhTag,
  verified: PhSealCheck,
  chart_pie: PhChartPieSlice,
  wallet: PhWallet,
  home: PhHouse,
}

export const modernIcons = {
  success: CircleCheck,
  error: CircleX,
  warning: TriangleAlert,
  info: Info,
  question: CircleQuestionMark,
}

export function isHighlight(name) {
  return Object.prototype.hasOwnProperty.call(highlightIcons, name)
}
